global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # DevOps Agent metrics (if we add a metrics endpoint)
  - job_name: 'devops-agent'
    static_configs:
      - targets: ['devops-agent:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL metrics (would need postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Node exporter for system metrics (if added)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker container metrics (if cadvisor is added)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
